//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserRegistration.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblUser
    {
        const short minAge = 0;
        const short maxAge = 100; 
        [Required]
        public int UserID { get; set; }
        [Required]
        [Display(Name="First Name")]
        public string FirstName { get; set; }
        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        [Required]
        [System.Web.Mvc.Remote("EmailExists", "Validation", ErrorMessage = "Email already exists")]
        public string Email { get; set; }
        [Range(minAge,maxAge)]
        public int Age { get; set; }

        public tblUser UpdateUserInfo(tblUser pNewUserInfo)
        {
            this.FirstName = pNewUserInfo.FirstName;
            this.LastName = pNewUserInfo.LastName;
            this.Email = pNewUserInfo.Email;
            this.Age = pNewUserInfo.Age;
            return this;
        }
    }
}
